# general settings
name: DeflareMamba_flare7kpp_baseline_option.yml
model_type: DeflareModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Flare7Kpp
    type: Flare7kpp_Pair_Loader
    image_path: /root/autodl-tmp/data/Flickr24K
    scattering_dict:
      Flare7k_scattering: /root/autodl-tmp/data/Flare7Kpp/Flare7K/Scattering_Flare/Compound_Flare
      Real_scattering1: /root/autodl-tmp/data/Flare7Kpp/Flare-R/Compound_Flare
    reflective_dict: # you can also comment this part to get more robust result
      Flare7k_reflective: /root/autodl-tmp/data/Flare7Kpp/Flare7K/Reflective_Flare
      Real_reflective1: ~
    light_dict:
      Flare7k_light: /root/autodl-tmp/data/Flare7Kpp/Flare7K/Scattering_Flare/Light_Source
      Real_light1: /root/autodl-tmp/data/Flare7Kpp/Flare-R/Light_Source
    data_ratio: [0.5, 0.5] # the ratio should be like [0.6, 0.4], [0.7, 0.3]
    transform_base:
      img_size: 512
    transform_flare:
      scale_min: 0.8
      scale_max: 1.5
      translate: 300
      shear: 20
    mask_type: ~

    
    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: flare_test
    type: Image_Pair_Loader
    dataroot_gt: /root/autodl-tmp/data/val/gt
    dataroot_lq: /root/autodl-tmp/data/val/input
    gt_size: 512

# network structures
network_g:
  type: DeflareMamba
  upscale: 1
  in_chans: 3
  output_ch: 6
  img_size: 512
  img_range: 1.
  d_state: 10
  depths: [1,2,4, 4, 4,2,1]
  embed_dim: 40
  mlp_ratio: 1.

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [200000]
    gamma: 0.5

  out_deflare: True
  ema_decay: 0.9
  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  l1_opt:
    type: MSELoss
    loss_weight: 0.5

  perceptual:
    type: L_percepture
    loss_weight: 0.5

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
